# Generated by Django 3.2.25 on 2024-04-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_alter_object_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='views',
            field=models.IntegerField(blank=0, default=0),
        ),
    ]
